name: Code & Documentation Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  code-checking:
    name: Run Code-Checking and Check Doxygen-Comments
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set Up Environment
      run: |
        sudo apt update
        sudo apt install -y make cppcheck doxygen python2-minimal

    - name: Load Default Configuration
      run: make default_config_defconfig

    - name: Run Code-Checking
      run: make verif

    - name: Save Code-Checking log as artifact
      if: failure() && matrix.job != 'check-doxygen-comments'
      uses: actions/upload-artifact@v4
      with:
        name: code-checking-log
        path: build/code-checking.log

    - name: Check Doxygen-Comments
      run: ./update-doc.sh

    - name: Save Doxygen log as artifact
      if: failure() && matrix.job != 'run-code-checking'
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-log
        path: build/doxygen/doxygen.log

    - name: Save Doxygen Output as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-output
        path: build/doxygen

  deploy:
    if: github.event_name == 'push'
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: code-checking

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Doxygen Output Artifact
      uses: actions/download-artifact@v4
      with:
        name: doxygen-output
        path: build/doxygen

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/doxygen/html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
