name: Clang Format Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    format-check:
        name: Run Clang Format
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Clang Format

              run: |
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 19
                  sudo apt-get install -y clang-format-19

            - name: Find and Format Files
              run: |
                  clang-format-19 --version 
                  ./format.sh

            - name: Check for Uncommitted Changes
              run: |
                  if [[ -n $(git status --porcelain) ]]; then
                    echo "Formatting required! Some files were modified."
                    git diff
                    exit 1
                  else
                    echo "All files are properly formatted."
                  fi
